### PR TITLE
Remove and update dependencies

### PR DESCRIPTION
**Pull request by roderickhsiao**
@longlho @redonkulus 

We are not using lodash in this package and url can be access by native node module.
Update several devDependencies and sort variables.

### CODE REVIEW

**Comment by Edmondton** [comment]
@roderickhsiao - update package version

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by roderickhsiao** [comment]
@Edmondton updated. thanks

**Comment by Edmondton** [comment]
:+1: - merge once travis passes

**Comment by redonkulus** [comment]
:+1:

**Comment by Edmondton** [comment]
@roderickhsiao - lodash is being used.  used by the files in the lib folder.  i would put back the lodash deps

**Comment by roderickhsiao** [comment]
added back

**Comment by roderickhsiao** [comment]
@Edmondton I think we will need to run `npm publish`, I don't have access to publish package.

**Comment by Edmondton** [comment]
@roderickhsiao - i can publish right now

**Comment by roderickhsiao** [comment]
awesome thanks!

**Pull request merged**
