### PR TITLE
compile jsx to js in components-dist

### PR DESCRIPTION
**Pull request by longlho**
@Edmondton 

I bumped major as well since it's a breaking change

### CODE REVIEW

**Comment by Edmondton** [comment]
Good additions long Ho. I acknowledge your work and feedback. :+1:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by longlho** [comment]
@Edmondton can u publish also pretty please :)

**Comment by Edmondton** [comment]
@longlho you wish has been granted.  Thank you for your feedback and comments.  I acknowledge your comments and feedback.

**Pull request merged**
